# Tell Travis CI we're using PHP
language: php

# Using trusty instead of precise because we don't need PHP 5.2 or 5.3 anymore.
dist: trusty

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin
    - $HOME/deployment-targets

branches:
  only:
    - master
    - develop
    - /^\d+\.\d+$/

env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - PATH="$(pwd):$TRAVIS_BUILD_DIR/vendor/bin:$HOME/.composer/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$(pwd)"

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist."
  - |
    # Raise PHP memory limit to 2048MB
    echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - nvm install
  - composer install --no-interaction
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - npm run build:js
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

jobs:
  fast_finish: true
  allow_failures:
    - env: ALLOW_FAILURES=1
  include:
    - stage: deploy
      name: GitHub Release
      php: "5.4"
      env: DEV_LIB_SKIP=phpcs,eslint,xmllint,phpsyntax,phpunit
      install:
        - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        - chmod +x wp-cli.phar
        - mv wp-cli.phar wp
        - wp package install wp-cli/dist-archive-command
        - (cd $(wp package path wp-cli/dist-archive-command) && git pull) # Temporary workaround.
        - nvm install
        - npm install
      script:
        #- set -e # Fail build as soon as one of the following commands fails.
        - npm run build:js
        - wp dist-archive ./ $(pwd)/build/composer.zip --create-target-dir
        - wp dist-archive ./ ./build/composer.zip --create-target-dir
        - wp dist-archive ./ build/composer.zip --create-target-dir
        - wp dist-archive ./ ./composer.zip --create-target-dir
        - wp dist-archive $(pwd) ./composer.zip --create-target-dir
        - wp dist-archive $(pwd) $(pwd)/build/composer.zip --create-target-dir
        - composer install --no-interaction --no-dev
        - wp dist-archive $(pwd) $(pwd)/build/amp.zip --create-target-dir
        - echo "Deploying to GitHub releases ..."
      after_script: false
      deploy:
        provider: releases
        api_key:
          secure: jxY493idtkiiFfLRkMrx66hfZ2kpeqowFgbAl525/WwZ+0KNaSwMlQuqzGYNbwbrqtpr9M82Y4QgV0jbBcJO8jjf6TZ6ZvWjRiBOFxkySYP6mKwtV+zlPjb/QcKKd9/T+TcoMtREkhXX7/vMqatCjAm9OwGVmQ0TFd8/NwM5aHIwnMA7F9/F/RkloL/3Kej/a6TMnBwEeroalYRLhXSldooli3N31xcEUSWFlosdpL3rg4x9XER1IbdsnfnAm7zvf18o8AWsJKTA8PO9VyM9TIZVPk3wNrTgLpAsQ0140z8QPa/KRfZHr45oE3a/WkPXmG75ptqSP2XE1xKHGVN/XnfvydG5xCP8gyZvwkn1H66RP3PLAm1d7yCFV/ogZVCAb8TBaLpyvwdyyFT67c/Uay4obzkGoCze4gjOWj1FILQ6wqe2zGDQkzEr0Co3ZLF8+hrq7sNVwuDzgJfocwiEIHgK1P1rUcdbceM/2GEjv7GofvjX80gXpGY2yP8EIo+baHjYU9SlOgDB76LbA6H0fQo/H/XrGTlQMdexkeubEicZsAQYrjh8JEOEtE1y6JHSXwwIq7gWhDC5S2LGB9GVZwYFloDLHV5RCXaeUZY/W7AXcMbvd3BnNEp5+lMMBLNJT0taev/XKGBoKlIWtZPXjX1AYl+TvuiFyEHFqzQOG3o=
        file:
          - build/amp.zip
          - build/composer.zip
        skip_cleanup: true
        draft: true
        name: "Nighty night"
        body: "This is a nightly build."
        prerelease: true
        on:
          repo: swissspidy/amp-wp
