# Tell Travis CI we're using PHP
language: php

# Using trusty instead of precise because we don't need PHP 5.2 or 5.3 anymore.
dist: trusty

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin
    - $HOME/deployment-targets

branches:
  only:
    - master
    - develop
    - /^\d+\.\d+$/

env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - PATH="$(pwd):$TRAVIS_BUILD_DIR/vendor/bin:$HOME/.composer/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$(pwd)"

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist."
  - |
    # Raise PHP memory limit to 2048MB
    echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - nvm install
  - composer install --no-interaction
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - npm run build:js
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

jobs:
  fast_finish: true
  allow_failures:
    - env: ALLOW_FAILURES=1
  include:
    - stage: deploy
      name: GitHub Release
      php: "5.4"
      env: DEV_LIB_SKIP=phpcs,eslint,xmllint,phpsyntax,phpunit
      install:
        - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        - chmod +x wp-cli.phar
        - mv wp-cli.phar wp
        - wp package install wp-cli/dist-archive-command
        - (cd $(wp package path wp-cli/dist-archive-command) && git pull) # Temporary workaround.
        - nvm install
        - npm install
      script:
        #- set -e # Fail build as soon as one of the following commands fails.
        - npm run build:js
        - (cd .. && wp dist-archive $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/build/composer.zip --create-target-dir)
        - composer install --no-interaction --no-dev
        - (cd .. && wp dist-archive $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/build/amp.zip --create-target-dir)
      after_script: false
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "Pascal Birchler"
        - git config --local user.email "pascalb@google.com"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%dT%H%M%SZ')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key:
          secure: ofY/CEH/yNPv2VpsyR9Ej6nM3t1jZFizn0cbdNY4P+Fx5es9DK+F67OjGQaKRCWL/XIe47gAAqw3YHbD2lPFP9ipV+eqgVK7dY0CD7FL13+Dt7eENpr8BDmAo3McxLTVhezumOKkNRexQYuj7dAMkm4JbniEG/IZIx4+xyQ1homBbD3AJCNXkykR5JU78Jz7NW6MdMFdhS/iwZzSSBdkioVzRdMIvVu9of7g8TOqKuvlc077dTEFzjuwVuihnrc41PtHxYBizmphpHABSKxSLd87JYqwRJi4WqsSQYmgyJc0oTe13i9NrT0vHrlbNZDpBkKKjKjr9h54a6dSipj/3/DXl+rIDBEjXVkKG2q8xlyiEUv88ONfBw6UK2fgOVv8TtboafHXWt6RH/17t4FSTXO78eVXzILo7CACOsHqrYq5X7NEwULTYKWJx622LRYZ3eKRmIsi/6yg+5Rcsunzy2Sw68jPxNSp8yDtmRBT6SSmmRZOCyH0dUBUkNIQQaPND1631kax5ZdbT9OQpiQkcfVQRUH0EHmlqko2FvF4EgmH3EgbmYtvXhpQRh27l1dwJFzxPFISnRPyDp/r1W0ajhU02bbvYjGi8F+ypBDmLciJUBiI4heP323H1rDw0GcX7avy/bBhWVD5rCRMt74gYIa4qXxei30S7iXbIDsjA0o=
        file:
          - build/amp.zip
          - build/composer.zip
        skip_cleanup: true
        draft: true
        name: "Nightly build"
        body: "This is a nightly build."
        prerelease: true
        on:
          repo: swissspidy/amp-wp
          all_branches: true
